title:            Evnton
description:      Evnton's blog.
url:              http://evnton.me
signoff:          Evnton
google_analytics: UA-55320040-1

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Contact
    url:          /contact
  - name:         Twitter
    url:          https://twitter.com/evnton
    external:     true
  - name:         GitHub
    url:          http://github.com/evnton
    external:     true
permalink:        pretty
paginate:         20
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Gems
gems: [jekyll-paginate]
